# This YAML file specifies the yarnPath configuration for the project.
# The yarnPath property specifies the path to the yarn binary that should be used for this project.
yarnPath: .yarn/releases/yarn-4.0.2.cjs
